### PR TITLE
panda controller sleep time correction

### PR DESCRIPTION
**Pull request by joshismayank**

### CODE REVIEW

**Comment by peasant98** [comment]
LGTM, but we recommend using the `PandaController` in `RobotController.py`.

**Comment by peasant98** [comment]
Check out https://github.com/HIRO-group/ros_robotic_skin/blob/0deba502e589a076dbab0df20cbeb6f095a9add6/scripts/controllers/RobotController.py#L105. In fact, we should update these files so PandaController.py actually has what we want.

**Comment by watakandai** [comment]
Definitely, you should use `PandaController` in `RobotController.py`

**Comment by watakandai** [comment]
@joshismayank Could you make a change and push once more? We can merge it asap

**Comment by peasant98** [comment]
@joshismayank A PR has been raised deleting the old PandaController.py file. This function with the sleep time correction is non-existent in the new code.

**Pull request closed without merging**
